apiVersion: v1
kind: Secret
metadata:
  name: web-tls-secret
  namespace: web-app
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDQzCCAiugAwIBAgIUHrdZPK7ZB97th0IO+rmIth/IirswDQYJKoZIhvcNAQEL
    BQAwIDEeMBwGA1UEAwwVZ2F0ZXdheS53ZWIuazhzLmxvY2FsMB4XDTI2MDExMzEz
    MTIyNloXDTI3MDExMzEzMTIyNlowIDEeMBwGA1UEAwwVZ2F0ZXdheS53ZWIuazhz
    LmxvY2FsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArmCqDSQKWmUd
    pnNvqbktqk1TH9CImjC6Da3AHGO5u20JZxUpZaU8qf3jmajeJPFqOc7kIBGwhXEm
    DCzmgfDAB3eWGp2o/7DUG2QW1qGgiiqMx13N9iBpZBdqZwIgrTtz92f4QlbeSSIl
    ChyrJeZH4Y4uc/hlhutQkFuurSgV677gcn5fCwcGbTObP8HgUTn2mIubEnYXlDop
    MGILdkAfgQsQLmYeoUKUCGDMFjdcDnJNdlAekq15oGD3u13T5C6hFbJb0CSdFsRp
    HSSe7vOdBui5At/p1z71VFOs+bklpxrg4uzBFsJGyVdnCmOdy76IUDvxUd5HLpro
    C6RVUFMcfQIDAQABo3UwczAdBgNVHQ4EFgQUydw5juVDoP1+ioq0CvPtfKo7iwEw
    HwYDVR0jBBgwFoAUydw5juVDoP1+ioq0CvPtfKo7iwEwDwYDVR0TAQH/BAUwAwEB
    /zAgBgNVHREEGTAXghVnYXRld2F5LndlYi5rOHMubG9jYWwwDQYJKoZIhvcNAQEL
    BQADggEBAFECjtnfSrnppEbdnNr0VrFE6cpBUcBoHzMDPy8FYvMYiFZWDHk95y/a
    OXntjxspwha8yYImQP/WAGhcFRaHaX03wVuCcP2tE7RQaI82p3DyuUv+CbOuQ/L3
    o9WT3GcAdygcfXARQIDkpX4F09ov4y+bib0COnkMaM5JDav/YOSzKE3A5Ix67/67
    09h8PdNPfGk0+gNGmFr34NIXK7ejkfMOC/Ke2VJoxoS4pVSsPXD2jTbGTJGKgBG7
    fsL0mDmi85cr8JNSEd0vgCNsorV3pEeUoVdG1hRwNFl0/hHCp3CBgCz5KznUhH7R
    rHCJZYI/hkDg1pISkGjTZKq3yLry77U=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCuYKoNJApaZR2m
    c2+puS2qTVMf0IiaMLoNrcAcY7m7bQlnFSllpTyp/eOZqN4k8Wo5zuQgEbCFcSYM
    LOaB8MAHd5Yanaj/sNQbZBbWoaCKKozHXc32IGlkF2pnAiCtO3P3Z/hCVt5JIiUK
    HKsl5kfhji5z+GWG61CQW66tKBXrvuByfl8LBwZtM5s/weBROfaYi5sSdheUOikw
    Ygt2QB+BCxAuZh6hQpQIYMwWN1wOck12UB6SrXmgYPe7XdPkLqEVslvQJJ0WxGkd
    JJ7u850G6LkC3+nXPvVUU6z5uSWnGuDi7MEWwkbJV2cKY53LvohQO/FR3kcumugL
    pFVQUxx9AgMBAAECggEAAoldb+YqUGOlfsUHHCJEIR9m1ND6a7kcZmk0oN/Cf+Yi
    JjcPQcSZkU95fsQPbId70sNzsL5mdvUiZzhFUiE9FIlkzED8MwamJI/cKoXHXrsn
    uRlgOZ2sasxRu+syq9JwPr/AbhadZ9WbUakBGa1ei6Vp1Oi0HAuoQbFTun5uyIhu
    zUq/Vv9x40SKhoI2nkYFvV+3mQmoiBDqoGv8aOdNeGcm+k8quMpxIw3jwgVtNxhi
    hjcG61RiVknVIubCthOUYuICxBXGKvVv4wnnmMa2ZLweUt6Nb4o3086GftrMxcu+
    +GTarBu4gob7Pxame9rxMis3eJMvREHQoz/pY48mcQKBgQDYmjP4Z3+r/RSCeQz+
    dIGsbWFoceudwZf0nAR7Zbhqiw1/tPz4dflHSZ370IQI4/ZpKOB5lwLNP/M2W58a
    ALsEVa5XCFCNktTSyI2T8T6I0ML19dWpVrsLuCDHlvCRWTNdRTMYVn1vSxbVPwVI
    TTHjtTFonQ6AiktZxr/cA3U4QwKBgQDOGFJ3WywsPPw+RIn5ARFwSH23+Vsmpuv0
    fRt1sEtGw1biEsr5yIMkmck4INy0ackm6o7Y+37nGA8HWmbuS74jyWWt7f5rsYNp
    FuI9eJyY1eAyUNUuCb0C2G8lGtPHWCX3OeDvvjGzFdcv2eWcEmVVib6L/BCfw+LU
    KNFTfWpsPwKBgExvhj13kJdJ1O4B97LnvEbzxncMFIB0K8J3OCGvkLeQYHAbl1W6
    lAAzG1wchit4/qC3exeNUcDKe3JIPMn5TgXGkqJF3d9H3HCRs1xsuoufV91iJkb+
    wzzseizUuAoitzyHyfMhulwG3ITeG2gbTaq0az4mhlKX+uUwfM4QLlJvAoGAKj7+
    GI1N3ruZkUIHbk1zv6p8asvojWHGGFXU3SkIJTdBhhIIHW+mwkfr4V+LHkhY/Wsz
    YPMcrk5WNlGnq81G6psMBr00W+sFXvNb6PHiV8nvrSC4sjk4z26CSf7XzpMZJTZu
    D3bTRTyC4cIuuPFkaEZWEufWmIlU49yCHDUnLY0CgYEAiwGHfG+Jg2fwDbOgwV2w
    LWVFMvwG9l9D3zaN8LTSBCybNV+Ivlwc1npBRU6DXM4/9dQ82XKE0rud6RIYVKXe
    jL9icPMCaknE93Iv79Oj7Xqyn4jGkkcecO12+KBa1Pb7eCqfEEpg6HSKscA5nfcq
    XDVyE23sn8vPqUND4ovEyLk=
    -----END PRIVATE KEY-----
