apiVersion: v1
kind: Secret
metadata:
  name: web-tls-secret
  namespace: web-app
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    -----END PRIVATE KEY-----
